.travis.yml, Pipfile.lock, news/11.bugfix, news/11.feature, setup.cfg, src/vistir/misc.py, tests/test_misc.py, tests/test_path.py
Update vistir.misc.run with multiple enhancements
- Allow `run` to return objects which include the output (fixes #9)
- Add a spinner to `run` calls (fixes #8)
- Add nonblocking calls (fixes #10)
=> Update vistir.misc.run with multiple enhancements

news/12.feature, news/13.feature, setup.cfg, src/vistir/misc.py
- Fixes #12
- Fixes #13
- Allows spinner to be disabled with `vistir.misc.run(...nospin=True)`
- Allows printing output in real time to be disabled with
`vistir.misc.run(verbose=False)`
=> Make spinner and output printing optional

news/26.feature.rst, news/27.bugfix.rst, news/28.bugfix.rst, src/vistir/__init__.py, src/vistir/backports/tempfile.py, src/vistir/compat.py, src/vistir/contextmanagers.py, src/vistir/misc.py, src/vistir/path.py, src/vistir/spin.py, src/vistir/termcolors.py
- Modified spinners to prefer to write to ``sys.stderr`` by default
- avoid writing ``None``
- fixed an issue with signal registration on Windows
- Fixed a bug with string encodings for terminal colors when using
spinners
- Implemented ``vistir.misc.create_tracked_tempdir``, which allows for
automatically cleaning up resources using weakreferences at interpreter exit.
- Fixes #26
- Fixes #27
- Fixes #28
=>  Fix spinner and encoding issues

README.rst, docs/conf.py, docs/quickstart.rst, news/38.feature.rst, setup.cfg, src/vistir/compat.py, src/vistir/misc.py, src/vistir/path.py, src/vistir/spin.py, tests/test_misc.py, tests/test_path.py
- Backport python/cpython#10320 (not yet merged) for better cleanup on
`shutil.rmtree` failure (using `os.chflags`)
- Add compatibility shims for `PermissionError` and `IsADirectory`
exceptions
- General cleanup
- Fixes #38
=> Backport new readonly removal features from python

.travis.yml, README.rst, appveyor.yml, docs/conf.py, docs/quickstart.rst, news/48.feature.rst, news/49.bugfix.rst, news/51.feature.rst, news/52.feature.rst, setup.cfg, src/vistir/__init__.py, src/vistir/compat.py, src/vistir/contextmanagers.py, src/vistir/misc.py, src/vistir/path.py, src/vistir/spin.py, tests/conftest.py, tests/test_contextmanagers.py, tests/test_path.py, tests/test_spinner.py
- Also fix a bug with error reporting during `_create_subprocess`
failures
- Adds a stream wrapper using `TextIOWrapper` via
`vistir.misc.StreamWrapper`
- Adds `vistir.misc.get_wrapped_stream()` function to wrap existing
streams
- Adds `vistir.contextmanagers.replaced_stream()` to temporarily replace
a stream
- Fixes #49
- Closes #48
=> Provide a way to capture or wrap streams

news/53.feature.rst, src/vistir/__init__.py, src/vistir/compat.py, src/vistir/path.py, tests/test_path.py
- Filesystem paths are no longer explicitly bytes encoded
- Encode and decode according to `sys.getfilesystemencoding()`
- Handle errors according to `sys.getfilesystemencodeerrors()` where available
- Use `surrogatepass` on windows+python 3.2+, `replace` when encoding on
windows+python2, `escape` when decoding on windows+python2
- Use `surrogateescape` on posix when `getfilesystemencodeerrors()` is not available
=> Add support for proper filesystem encodings

news/46.bugfix, src/vistir/path.py
Fix ```FileNotFoundError``` is not imported from compat for rmtree
Fix ```rmtree``` doesn't ignore file or directory not found error
Found it in https://github.com/pypa/pipenv/pull/3354
=> Fix bugs in rmtree

src/vistir/misc.py
Previously, they were accidentally being discarded during the encoding step.
Resolves #55
=> Use environment variables provided as an argument to run()

Pipfile.lock, README.rst, news/57.feature.rst, pyproject.toml, setup.cfg, src/vistir/__init__.py, src/vistir/cursor.py, src/vistir/spin.py
=> Remove dependency on `cursor`

src/vistir/path.py
FileNotFoundError does not exist on Python 2.
=> rmtree: import FileNotFoundError from compat

news/69.bugfix.rst, src/vistir/misc.py, src/vistir/spin.py
- Fixes #69
- avoids double encoding text on python 2
=> Fix spinner output encoding

news/65.bugfix.rst, tests/test_path.py
Fix test path generation lengths
- Include hypothesis assumption of path length `< 255`
- Fixes #65
=> Fix test path generation lengths

news/72.bugfix.rst, pyproject.toml
Fix temporary directory rmtree error handler
- Fixes #72
=> Fix temporary directory rmtree error handler

setup.cfg, src/vistir/compat.py
Remove complex version markers and runtime version checking
for unsupported versions between Python 2.7 and Python 3.4+.
The logic was wrong, requiring backports.functools_lru_cache
on Python 3.4 when the stdlib function was acceptable.
Fixes https://github.com/sarugaku/vistir/issues/63
=> compat: Remove backports from Python 3.4

news/74.bugfix.rst, src/vistir/backports/tempfile.py, test_compat.py
- Fixes #74
- add fsencode and fsdecode test
=> Fix backport fsencode reference

news/78.bugfix.rst, src/vistir/misc.py
The issue
According to the existing code, locale_encoding of 302 line is fixed as ascii, and it does not follow system encoding value.
It can be a bug in an area that uses encoding in other languages ​​not English.
The fix
replace locale.getdefaultlocale with locale.getdefaultencoding because locale.getdefaultencoding is not exist
=> * Replace to locale.getdefaultlocale because there is no locale.getdefaultencoding

news/88.bugfix.rst, src/vistir/_winconsole.py, src/vistir/misc.py, src/vistir/path.py
- Pass `fileno` correctly to `ConsoleWrapper`
- Fix encoding fallbacks for `StreamWrapper`
- Don't re-wrap streams that are already wrapped for color
- Fixes #88
=> Fix stream color wrappers on windows

news/90.feature.rst, src/vistir/_winconsole.py, src/vistir/path.py
- Shortened windows paths should be expanded by `normalize_path`
- Fixes #90
=> Add function to expand shortened paths on windows

news/95.bugfix.rst, news/96.bugfix.rst, src/vistir/misc.py, src/vistir/spin.py
- Fix deadlock when fielding `CTRL_BREAK_EVENT` while spinner is running
- Fix failure to raise handled exceptions in `vistir.misc.run`
- Fixes #95
- Fixes #96
=> Fix deadlock / race conditions on windows

tests/test_path.py
A single UTF-8 character may be encoded to several bytes. For Linux,
the typical maximum component length is 255 bytes.
This should fix occasional failures like #65.
=> Account for encoded length when limiting path components

.codecov.yml, .pre-commit-config.yaml, Pipfile, Pipfile.lock, news/102.feature.rst, setup.cfg, src/vistir/_winconsole.py, src/vistir/contextmanagers.py, tests/test_contextmanagers.py, tests/test_path.py, tests/test_spinner.py, tests/utils.py
- Reduce dependency count
- Add fallback to urllib for `vistir.contextmanagers.open_file`
- Update tests to cover the new case
- Fix permissions issue when removing readonly files (we weren't making
directories executable before cleaning up)
- Add `requests` extra
- Update copyright notice in what used to be a click module but is
vastly expanded
Signed-off-by: Dan Ryan <dan.ryan@canonical.com>
=> Remove reliance on requests for file downloads

setup.cfg
Upstream releases have broken Python 3.4
Closes https://github.com/sarugaku/vistir/issues/98
=> setup.cfg: Add colorama constraint !=0.4.2

Pipfile.lock, news/100.bugfix.rst, setup.cfg, src/vistir/path.py, tests/test_path.py
- Use appropriate error-handling encoders and directly urlencode paths before
converting to a `file://` url
- Vistir's compat filesystem encoding will allow us to manage the
surrogates properly on windows during the decoding step
- Added additional functionality for `url_to_path` conversions to make
sure we unquote urls that may have been quoted here
- Fixes #100
Signed-off-by: Dan Ryan <dan.ryan@canonical.com>
=> Fix surrogate handler for filename->url conversion

.azure-pipelines/templates/run-tests.yml, .github/workflows/ci.yml, .pre-commit-config.yaml, Pipfile.lock, azure-pipelines.yml, news/110.bugfix.rst, src/vistir/_winconsole.py, src/vistir/backports/surrogateescape.py, src/vistir/compat.py, src/vistir/contextmanagers.py, src/vistir/misc.py, src/vistir/path.py, src/vistir/spin.py, tests/fixtures/gutenberg_document.txt, tests/strategies.py, tests/test_contextmanagers.py, tests/test_misc.py, tests/test_path.py
- Allow graceful failures to `chmod` new files in
`contextmanagers.atomic_open_for_write`
- Add test
- Add type hints
- Improve generative tests
- Fix unicode converson on mac
- Respect unicode normalization on MacOS (azure test failures preventing merge)
- Remove unnecessary functionality
- Improve subprocess calls and pass encoding arguments
- Fix windows console formatting and path comparisons
- Fix broken encoding on azure
- Avoid reading subprocess output after closing (azure test failures preventing merge)
- Avoid hangs due to reading closed subprocess `stdout`
- Format documentation
- Add github CI to avoid dealing with azure
- Fixes #110
Signed-off-by: Dan Ryan <dan.ryan@canonical.com>
=> Handle chmod failures in atomic_open_for_write

README.rst, src/vistir/misc.py, src/vistir/spin.py
Remove a few functions that are either simply copied from other libraries or can be easily replaced with a one-liner.
=> Add deprecation warnings
